import java.util.*;

class Output{

          static HashMap<String, ArrayList<Figura> > mapa = new HashMap<String, ArrayList<Figura> >();
          static ArrayList<Figura> temp;
          public static HashMap<String, ArrayList<Figura> > out (){
                    read();
                    return mapa;
          }
          public static void read(){
                    Circle corpo = new Circle ("corpo", 40, 50, 25);
                    corpo.putAtribute("color", "YELLOW");
                    corpo.putAtribute("filled", "True");
                    Triangle boca = new Triangle("boca",40,50,65,35,65,65);
                    boca.putAtribute("color", "BLACK");
                    boca.putAtribute("filled", "True");
                    temp = new ArrayList<Figura>();
                    temp.add(corpo);
                    temp.add(boca);
                    mapa.put("player",temp);
                    Rectangle w1 = new Rectangle("w1", 0, 892,900,6);
                    w1.putAtribute("color", "BLUE");
                    w1.putAtribute("thickness", "2");
                    Rectangle w2 = new Rectangle("w2", 0, 0,800,6);
                    w2.putAtribute("color", "BLUE");
                    w2.putAtribute("thickness", "2");
                    Rectangle w3 = new Rectangle("w3", 792, 0,6,900);
                    w3.putAtribute("color", "BLUE");
                    w3.putAtribute("thickness", "2");
                    Rectangle w4 = new Rectangle("w4", 0, 0,6,900);
                    w4.putAtribute("color", "BLUE");
                    w4.putAtribute("thickness", "2");
                    Rectangle meio1 = new Rectangle("meio1", 397, 0,6,150);
                    meio1.putAtribute("color", "BLUE");
                    meio1.putAtribute("thickness", "2");
                    Rectangle meio2 = new Rectangle("meio2", 315, 250,170,6);
                    meio2.putAtribute("color", "BLUE");
                    meio2.putAtribute("thickness", "2");
                    Rectangle topR1 = new Rectangle("topR1", 500, 90,70,60);
                    topR1.putAtribute("color", "BLUE");
                    topR1.putAtribute("thickness", "2");
                    Rectangle topR2 = new Rectangle("topR2", 660, 90,50,60);
                    topR2.putAtribute("color", "BLUE");
                    topR2.putAtribute("thickness", "2");
                    Rectangle topR3 = new Rectangle("topR3", 660, 240,50,170);
                    topR3.putAtribute("color", "BLUE");
                    topR3.putAtribute("thickness", "2");
                    Rectangle topL1 = new Rectangle("topL1", 230, 90,70,60);
                    topL1.putAtribute("color", "BLUE");
                    topL1.putAtribute("thickness", "2");
                    Rectangle topL2 = new Rectangle("topL2", 90, 90,50,60);
                    topL2.putAtribute("color", "BLUE");
                    topL2.putAtribute("thickness", "2");
                    Rectangle topL3 = new Rectangle("topL3", 90, 240,50,170);
                    topL3.putAtribute("color", "BLUE");
                    topL3.putAtribute("thickness", "2");
                    Rectangle meioR = new Rectangle("meioR", 567, 250,6,160);
                    meioR.putAtribute("color", "BLUE");
                    meioR.putAtribute("thickness", "2");
                    Rectangle meioL = new Rectangle("meioL", 234, 250,6,160);
                    meioL.putAtribute("color", "BLUE");
                    meioL.putAtribute("thickness", "2");
                    Rectangle meioMVer = new Rectangle("meioMVer", 397, 256,6,154);
                    meioMVer.putAtribute("color", "BLUE");
                    meioMVer.putAtribute("thickness", "2");
                    Rectangle meioML = new Rectangle("meioML", 240, 330,80,6);
                    meioML.putAtribute("color", "BLUE");
                    meioML.putAtribute("thickness", "2");
                    Rectangle meioMR = new Rectangle("meioMR", 487, 330,80,6);
                    meioMR.putAtribute("color", "BLUE");
                    meioMR.putAtribute("thickness", "2");
                    Rectangle meio2Baixo = new Rectangle("meio2Baixo", 315, 410,170,6);
                    meio2Baixo.putAtribute("color", "BLUE");
                    meio2Baixo.putAtribute("thickness", "2");
                    Rectangle grandL = new Rectangle("grandL", 6, 510,350,40);
                    grandL.putAtribute("color", "BLUE");
                    grandL.putAtribute("thickness", "2");
                    Rectangle grandR = new Rectangle("grandR", 446, 510,350,40);
                    grandR.putAtribute("color", "BLUE");
                    grandR.putAtribute("thickness", "2");
                    Rectangle meio2Baixo2 = new Rectangle("meio2Baixo2", 300, 640,200,6);
                    meio2Baixo2.putAtribute("color", "BLUE");
                    meio2Baixo2.putAtribute("thickness", "2");
                    Rectangle meio2BaixoV = new Rectangle("meio2BaixoV", 397, 646,6,80);
                    meio2BaixoV.putAtribute("color", "BLUE");
                    meio2BaixoV.putAtribute("thickness", "2");
                    Rectangle meio2BaixoL = new Rectangle("meio2BaixoL", 6, 640,200,6);
                    meio2BaixoL.putAtribute("color", "BLUE");
                    meio2BaixoL.putAtribute("thickness", "2");
                    Rectangle meio2BaixoR = new Rectangle("meio2BaixoR", 596, 640,200,6);
                    meio2BaixoR.putAtribute("color", "BLUE");
                    meio2BaixoR.putAtribute("thickness", "2");
                    Rectangle meioFinal = new Rectangle("meioFinal", 300, 810,200,6);
                    meioFinal.putAtribute("color", "BLUE");
                    meioFinal.putAtribute("thickness", "2");
                    Rectangle fimGordoL = new Rectangle("fimGordoL", 6, 735,200,80);
                    fimGordoL.putAtribute("color", "BLUE");
                    fimGordoL.putAtribute("thickness", "2");
                    Rectangle fimGordoR = new Rectangle("fimGordoR", 593, 735,200,80);
                    fimGordoR.putAtribute("color", "BLUE");
                    fimGordoR.putAtribute("thickness", "2");
                    Rectangle fimMeioL = new Rectangle("fimMeioL", 300, 720,6,90);
                    fimMeioL.putAtribute("color", "BLUE");
                    fimMeioL.putAtribute("thickness", "2");
                    Rectangle fimMeioR = new Rectangle("fimMeioR", 494, 720,6,90);
                    fimMeioR.putAtribute("color", "BLUE");
                    fimMeioR.putAtribute("thickness", "2");
                    temp = new ArrayList<Figura>();
                    temp.add(w1);
                    temp.add(w2);
                    temp.add(w3);
                    temp.add(w4);
                    temp.add(meio1);
                    temp.add(meio2);
                    temp.add(topR1);
                    temp.add(topR2);
                    temp.add(topR3);
                    temp.add(topL1);
                    temp.add(topL2);
                    temp.add(topL3);
                    temp.add(meioR);
                    temp.add(meioL);
                    temp.add(meioMVer);
                    temp.add(meioML);
                    temp.add(meioMR);
                    temp.add(meio2Baixo);
                    temp.add(grandL);
                    temp.add(grandR);
                    temp.add(meio2Baixo2);
                    temp.add(meio2BaixoV);
                    temp.add(meio2BaixoL);
                    temp.add(meio2BaixoR);
                    temp.add(meioFinal);
                    temp.add(fimGordoL);
                    temp.add(fimGordoR);
                    temp.add(fimMeioL);
                    temp.add(fimMeioR);
                    mapa.put("mapa",temp);
                    Circle c1 = new Circle ("c1", 50, 118, 8);
                    c1.putAtribute("color", "WHITE");
                    c1.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c1);
                    mapa.put("moeda1",temp);
                    Circle c2 = new Circle ("c2", 50, 186, 8);
                    c2.putAtribute("color", "WHITE");
                    c2.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c2);
                    mapa.put("moeda2",temp);
                    Circle c3 = new Circle ("c3", 50, 254, 8);
                    c3.putAtribute("color", "WHITE");
                    c3.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c3);
                    mapa.put("moeda3",temp);
                    Circle c4 = new Circle ("c4", 50, 322, 8);
                    c4.putAtribute("color", "WHITE");
                    c4.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c4);
                    mapa.put("moeda4",temp);
                    Circle c5 = new Circle ("c5", 50, 390, 8);
                    c5.putAtribute("color", "WHITE");
                    c5.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c5);
                    mapa.put("moeda5",temp);
                    Circle c6 = new Circle ("c6", 50, 458, 8);
                    c6.putAtribute("color", "WHITE");
                    c6.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c6);
                    mapa.put("moeda6",temp);
                    Circle c7 = new Circle ("c7", 50, 50, 8);
                    c7.putAtribute("color", "WHITE");
                    c7.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c7);
                    mapa.put("moeda7",temp);
                    Circle c8 = new Circle ("c8", 750, 118, 8);
                    c8.putAtribute("color", "WHITE");
                    c8.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c8);
                    mapa.put("moeda8",temp);
                    Circle c9 = new Circle ("c9", 750, 186, 8);
                    c9.putAtribute("color", "WHITE");
                    c9.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c9);
                    mapa.put("moeda9",temp);
                    Circle c10 = new Circle ("c10", 750, 254, 8);
                    c10.putAtribute("color", "WHITE");
                    c10.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c10);
                    mapa.put("moeda10",temp);
                    Circle c11 = new Circle ("c11", 750, 322, 8);
                    c11.putAtribute("color", "WHITE");
                    c11.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c11);
                    mapa.put("moeda11",temp);
                    Circle c12 = new Circle ("c12", 750, 390, 8);
                    c12.putAtribute("color", "WHITE");
                    c12.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c12);
                    mapa.put("moeda12",temp);
                    Circle c13 = new Circle ("c13", 750, 458, 8);
                    c13.putAtribute("color", "WHITE");
                    c13.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c13);
                    mapa.put("moeda13",temp);
                    Circle c14 = new Circle ("c14", 750, 50, 8);
                    c14.putAtribute("color", "WHITE");
                    c14.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c14);
                    mapa.put("moeda14",temp);
                    Circle c15 = new Circle ("c15", 109, 50, 8);
                    c15.putAtribute("color", "WHITE");
                    c15.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c15);
                    mapa.put("moeda15",temp);
                    Circle c16 = new Circle ("c16", 168, 50, 8);
                    c16.putAtribute("color", "WHITE");
                    c16.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c16);
                    mapa.put("moeda16",temp);
                    Circle c17 = new Circle ("c17", 227, 50, 8);
                    c17.putAtribute("color", "WHITE");
                    c17.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c17);
                    mapa.put("moeda17",temp);
                    Circle c18 = new Circle ("c18", 287, 50, 8);
                    c18.putAtribute("color", "WHITE");
                    c18.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c18);
                    mapa.put("moeda18",temp);
                    Circle c19 = new Circle ("c19", 345, 50, 8);
                    c19.putAtribute("color", "WHITE");
                    c19.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c19);
                    mapa.put("moeda19",temp);
                    Circle c20 = new Circle ("c20", 455, 50, 8);
                    c20.putAtribute("color", "WHITE");
                    c20.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c20);
                    mapa.put("moeda20",temp);
                    Circle c21 = new Circle ("c21", 691, 50, 8);
                    c21.putAtribute("color", "WHITE");
                    c21.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c21);
                    mapa.put("moeda21",temp);
                    Circle c22 = new Circle ("c22", 632, 50, 8);
                    c22.putAtribute("color", "WHITE");
                    c22.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c22);
                    mapa.put("moeda22",temp);
                    Circle c23 = new Circle ("c23", 573, 50, 8);
                    c23.putAtribute("color", "WHITE");
                    c23.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c23);
                    mapa.put("moeda23",temp);
                    Circle c24 = new Circle ("c24", 514, 50, 8);
                    c24.putAtribute("color", "WHITE");
                    c24.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c24);
                    mapa.put("moeda24",temp);
                    Circle c25 = new Circle ("c25", 109, 458, 8);
                    c25.putAtribute("color", "WHITE");
                    c25.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c25);
                    mapa.put("moeda25",temp);
                    Circle c26 = new Circle ("c26", 168, 458, 8);
                    c26.putAtribute("color", "WHITE");
                    c26.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c26);
                    mapa.put("moeda26",temp);
                    Circle c27 = new Circle ("c27", 227, 458, 8);
                    c27.putAtribute("color", "WHITE");
                    c27.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c27);
                    mapa.put("moeda27",temp);
                    Circle c28 = new Circle ("c28", 287, 458, 8);
                    c28.putAtribute("color", "WHITE");
                    c28.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c28);
                    mapa.put("moeda28",temp);
                    Circle c29 = new Circle ("c29", 345, 458, 8);
                    c29.putAtribute("color", "WHITE");
                    c29.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c29);
                    mapa.put("moeda29",temp);
                    Circle c30 = new Circle ("c30", 455, 458, 8);
                    c30.putAtribute("color", "WHITE");
                    c30.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c30);
                    mapa.put("moeda30",temp);
                    Circle c31 = new Circle ("c31", 691, 458, 8);
                    c31.putAtribute("color", "WHITE");
                    c31.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c31);
                    mapa.put("moeda31",temp);
                    Circle c32 = new Circle ("c32", 632, 458, 8);
                    c32.putAtribute("color", "WHITE");
                    c32.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c32);
                    mapa.put("moeda32",temp);
                    Circle c33 = new Circle ("c33", 573, 458, 8);
                    c33.putAtribute("color", "WHITE");
                    c33.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c33);
                    mapa.put("moeda33",temp);
                    Circle c34 = new Circle ("c34", 514, 458, 8);
                    c34.putAtribute("color", "WHITE");
                    c34.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c34);
                    mapa.put("moeda34",temp);
                    Circle c35 = new Circle ("c35", 400, 458, 8);
                    c35.putAtribute("color", "WHITE");
                    c35.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c35);
                    mapa.put("moeda35",temp);
                    Circle c36 = new Circle ("c36", 691, 186, 8);
                    c36.putAtribute("color", "WHITE");
                    c36.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c36);
                    mapa.put("moeda36",temp);
                    Circle c37 = new Circle ("c37", 632, 186, 8);
                    c37.putAtribute("color", "WHITE");
                    c37.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c37);
                    mapa.put("moeda37",temp);
                    Circle c38 = new Circle ("c38", 691, 186, 8);
                    c38.putAtribute("color", "WHITE");
                    c38.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c38);
                    mapa.put("moeda38",temp);
                    Circle c39 = new Circle ("c39", 573, 186, 8);
                    c39.putAtribute("color", "WHITE");
                    c39.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c39);
                    mapa.put("moeda39",temp);
                    Circle c40 = new Circle ("c40", 514, 186, 8);
                    c40.putAtribute("color", "WHITE");
                    c40.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c40);
                    mapa.put("moeda40",temp);
                    Circle c41 = new Circle ("c41", 455, 186, 8);
                    c41.putAtribute("color", "WHITE");
                    c41.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c41);
                    mapa.put("moeda41",temp);
                    Circle c42 = new Circle ("c42", 109, 186, 8);
                    c42.putAtribute("color", "WHITE");
                    c42.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c42);
                    mapa.put("moeda42",temp);
                    Circle c43 = new Circle ("c43", 168, 186, 8);
                    c43.putAtribute("color", "WHITE");
                    c43.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c43);
                    mapa.put("moeda43",temp);
                    Circle c44 = new Circle ("c44", 227, 186, 8);
                    c44.putAtribute("color", "WHITE");
                    c44.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c44);
                    mapa.put("moeda44",temp);
                    Circle c45 = new Circle ("c45", 286, 186, 8);
                    c45.putAtribute("color", "WHITE");
                    c45.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c45);
                    mapa.put("moeda45",temp);
                    Circle c46 = new Circle ("c46", 345, 186, 8);
                    c46.putAtribute("color", "WHITE");
                    c46.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c46);
                    mapa.put("moeda46",temp);
                    Circle c47 = new Circle ("c47", 404, 186, 8);
                    c47.putAtribute("color", "WHITE");
                    c47.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c47);
                    mapa.put("moeda47",temp);
                    Circle c48 = new Circle ("c48", 109, 592, 8);
                    c48.putAtribute("color", "WHITE");
                    c48.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c48);
                    mapa.put("moeda48",temp);
                    Circle c49 = new Circle ("c49", 168, 592, 8);
                    c49.putAtribute("color", "WHITE");
                    c49.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c49);
                    mapa.put("moeda49",temp);
                    Circle c50 = new Circle ("c50", 227, 592, 8);
                    c50.putAtribute("color", "WHITE");
                    c50.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c50);
                    mapa.put("moeda50",temp);
                    Circle c51 = new Circle ("c51", 287, 592, 8);
                    c51.putAtribute("color", "WHITE");
                    c51.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c51);
                    mapa.put("moeda51",temp);
                    Circle c52 = new Circle ("c52", 345, 592, 8);
                    c52.putAtribute("color", "WHITE");
                    c52.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c52);
                    mapa.put("moeda52",temp);
                    Circle c53 = new Circle ("c53", 455, 592, 8);
                    c53.putAtribute("color", "WHITE");
                    c53.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c53);
                    mapa.put("moeda53",temp);
                    Circle c54 = new Circle ("c54", 691, 592, 8);
                    c54.putAtribute("color", "WHITE");
                    c54.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c54);
                    mapa.put("moeda54",temp);
                    Circle c55 = new Circle ("c55", 632, 592, 8);
                    c55.putAtribute("color", "WHITE");
                    c55.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c55);
                    mapa.put("moeda55",temp);
                    Circle c56 = new Circle ("c56", 573, 592, 8);
                    c56.putAtribute("color", "WHITE");
                    c56.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c56);
                    mapa.put("moeda56",temp);
                    Circle c57 = new Circle ("c57", 514, 592, 8);
                    c57.putAtribute("color", "WHITE");
                    c57.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c57);
                    mapa.put("moeda57",temp);
                    Circle c58 = new Circle ("c58", 400, 592, 8);
                    c58.putAtribute("color", "WHITE");
                    c58.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c58);
                    mapa.put("moeda58",temp);
                    Circle c59 = new Circle ("c59", 50, 592, 8);
                    c59.putAtribute("color", "WHITE");
                    c59.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c59);
                    mapa.put("moeda59",temp);
                    Circle c60 = new Circle ("c60", 750, 592, 8);
                    c60.putAtribute("color", "WHITE");
                    c60.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c60);
                    mapa.put("moeda60",temp);
                    Circle c61 = new Circle ("c61", 400, 525, 8);
                    c61.putAtribute("color", "WHITE");
                    c61.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c61);
                    mapa.put("moeda61",temp);
                    Circle c62 = new Circle ("c62", 109, 692, 8);
                    c62.putAtribute("color", "WHITE");
                    c62.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c62);
                    mapa.put("moeda62",temp);
                    Circle c63 = new Circle ("c63", 168, 692, 8);
                    c63.putAtribute("color", "WHITE");
                    c63.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c63);
                    mapa.put("moeda63",temp);
                    Circle c64 = new Circle ("c64", 227, 692, 8);
                    c64.putAtribute("color", "WHITE");
                    c64.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c64);
                    mapa.put("moeda64",temp);
                    Circle c65 = new Circle ("c65", 287, 692, 8);
                    c65.putAtribute("color", "WHITE");
                    c65.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c65);
                    mapa.put("moeda65",temp);
                    Circle c66 = new Circle ("c66", 345, 692, 8);
                    c66.putAtribute("color", "WHITE");
                    c66.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c66);
                    mapa.put("moeda66",temp);
                    Circle c67 = new Circle ("c67", 455, 692, 8);
                    c67.putAtribute("color", "WHITE");
                    c67.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c67);
                    mapa.put("moeda67",temp);
                    Circle c68 = new Circle ("c68", 691, 692, 8);
                    c68.putAtribute("color", "WHITE");
                    c68.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c68);
                    mapa.put("moeda68",temp);
                    Circle c69 = new Circle ("c69", 632, 692, 8);
                    c69.putAtribute("color", "WHITE");
                    c69.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c69);
                    mapa.put("moeda69",temp);
                    Circle c70 = new Circle ("c70", 573, 692, 8);
                    c70.putAtribute("color", "WHITE");
                    c70.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c70);
                    mapa.put("moeda70",temp);
                    Circle c71 = new Circle ("c71", 514, 692, 8);
                    c71.putAtribute("color", "WHITE");
                    c71.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c71);
                    mapa.put("moeda71",temp);
                    Circle c72 = new Circle ("c72", 400, 855, 8);
                    c72.putAtribute("color", "WHITE");
                    c72.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c72);
                    mapa.put("moeda72",temp);
                    Circle c73 = new Circle ("c73", 50, 692, 8);
                    c73.putAtribute("color", "WHITE");
                    c73.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c73);
                    mapa.put("moeda73",temp);
                    Circle c74 = new Circle ("c74", 750, 692, 8);
                    c74.putAtribute("color", "WHITE");
                    c74.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c74);
                    mapa.put("moeda74",temp);
                    Circle c75 = new Circle ("c75", 400, 770, 8);
                    c75.putAtribute("color", "WHITE");
                    c75.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c75);
                    mapa.put("moeda75",temp);
                    Circle c76 = new Circle ("c76", 345, 770, 8);
                    c76.putAtribute("color", "WHITE");
                    c76.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c76);
                    mapa.put("moeda76",temp);
                    Circle c77 = new Circle ("c77", 455, 770, 8);
                    c77.putAtribute("color", "WHITE");
                    c77.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c77);
                    mapa.put("moeda77",temp);
                    Circle c78 = new Circle ("c78", 455, 855, 8);
                    c78.putAtribute("color", "WHITE");
                    c78.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c78);
                    mapa.put("moeda78",temp);
                    Circle c79 = new Circle ("c79", 510, 855, 8);
                    c79.putAtribute("color", "WHITE");
                    c79.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c79);
                    mapa.put("moeda79",temp);
                    Circle c80 = new Circle ("c80", 565, 855, 8);
                    c80.putAtribute("color", "WHITE");
                    c80.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c80);
                    mapa.put("moeda80",temp);
                    Circle c81 = new Circle ("c81", 620, 855, 8);
                    c81.putAtribute("color", "WHITE");
                    c81.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c81);
                    mapa.put("moeda81",temp);
                    Circle c82 = new Circle ("c82", 675, 855, 8);
                    c82.putAtribute("color", "WHITE");
                    c82.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c82);
                    mapa.put("moeda82",temp);
                    Circle c83 = new Circle ("c83", 730, 855, 8);
                    c83.putAtribute("color", "WHITE");
                    c83.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c83);
                    mapa.put("moeda83",temp);
                    Circle c84 = new Circle ("c84", 345, 855, 8);
                    c84.putAtribute("color", "WHITE");
                    c84.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c84);
                    mapa.put("moeda84",temp);
                    Circle c85 = new Circle ("c85", 290, 855, 8);
                    c85.putAtribute("color", "WHITE");
                    c85.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c85);
                    mapa.put("moeda85",temp);
                    Circle c86 = new Circle ("c86", 235, 855, 8);
                    c86.putAtribute("color", "WHITE");
                    c86.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c86);
                    mapa.put("moeda86",temp);
                    Circle c87 = new Circle ("c87", 180, 855, 8);
                    c87.putAtribute("color", "WHITE");
                    c87.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c87);
                    mapa.put("moeda87",temp);
                    Circle c88 = new Circle ("c88", 125, 855, 8);
                    c88.putAtribute("color", "WHITE");
                    c88.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c88);
                    mapa.put("moeda88",temp);
                    Circle c89 = new Circle ("c89", 70, 855, 8);
                    c89.putAtribute("color", "WHITE");
                    c89.putAtribute("thickness", "3");
                    temp = new ArrayList<Figura>();
                    temp.add(c89);
                    mapa.put("moeda89",temp);
                    Circle corpo1 = new Circle ("corpo1", 50, 50, 25);
                    corpo1.putAtribute("color", "BLUE");
                    corpo1.putAtribute("filled", "True");
                    Rectangle corpo2 = new Rectangle("corpo2", 25, 50,50,40);
                    corpo2.putAtribute("color", "BLUE");
                    corpo2.putAtribute("filled", "True");
                    Triangle corpo3 = new Triangle("corpo3",25,90,33,80,41,90);
                    corpo3.putAtribute("color", "BLACK");
                    corpo3.putAtribute("filled", "True");
                    Triangle corpo4 = new Triangle("corpo4",41,90,50,80,58,90);
                    corpo4.putAtribute("color", "BLACK");
                    corpo4.putAtribute("filled", "True");
                    Triangle corpo5 = new Triangle("corpo5",58,90,67,80,75,90);
                    corpo5.putAtribute("color", "BLACK");
                    corpo5.putAtribute("filled", "True");
                    Circle olho1 = new Circle ("olho1", 40, 50, 4);
                    olho1.putAtribute("color", "WHITE");
                    olho1.putAtribute("filled", "True");
                    Circle olho2 = new Circle ("olho2", 60, 50, 4);
                    olho2.putAtribute("color", "WHITE");
                    olho2.putAtribute("filled", "True");
                    Circle olho11 = new Circle ("olho11", 40, 52, 2);
                    olho11.putAtribute("color", "BLACK");
                    olho11.putAtribute("filled", "True");
                    Circle olho22 = new Circle ("olho22", 60, 52, 2);
                    olho22.putAtribute("color", "BLACK");
                    olho22.putAtribute("filled", "True");
                    Rectangle Borda = new Rectangle("Borda", 25, 25,50,65);
                    Borda.putAtribute("color", "GREEN");
                    Borda.putAtribute("hidden", "True");
                    temp = new ArrayList<Figura>();
                    temp.add(corpo1);
                    temp.add(corpo2);
                    temp.add(corpo3);
                    temp.add(corpo4);
                    temp.add(corpo5);
                    temp.add(olho1);
                    temp.add(olho2);
                    temp.add(olho11);
                    temp.add(olho22);
                    temp.add(Borda);
                    mapa.put("inimigo1",temp);
                    Circle corpo_1 = new Circle ("corpo_1", 750, 50, 25);
                    corpo_1.putAtribute("color", "RED");
                    corpo_1.putAtribute("filled", "True");
                    Rectangle corpo_2 = new Rectangle("corpo_2", 725, 50,50,40);
                    corpo_2.putAtribute("color", "RED");
                    corpo_2.putAtribute("filled", "True");
                    Triangle corpo_3 = new Triangle("corpo_3",725,90,733,80,741,90);
                    corpo_3.putAtribute("color", "BLACK");
                    corpo_3.putAtribute("filled", "True");
                    Triangle corpo_4 = new Triangle("corpo_4",741,90,750,80,758,90);
                    corpo_4.putAtribute("color", "BLACK");
                    corpo_4.putAtribute("filled", "True");
                    Triangle corpo_5 = new Triangle("corpo_5",758,90,767,80,775,90);
                    corpo_5.putAtribute("color", "BLACK");
                    corpo_5.putAtribute("filled", "True");
                    Circle olho_1 = new Circle ("olho_1", 740, 50, 4);
                    olho_1.putAtribute("color", "WHITE");
                    olho_1.putAtribute("filled", "True");
                    Circle olho_2 = new Circle ("olho_2", 760, 50, 4);
                    olho_2.putAtribute("color", "WHITE");
                    olho_2.putAtribute("filled", "True");
                    Circle olho_11 = new Circle ("olho_11", 740, 52, 2);
                    olho_11.putAtribute("color", "BLUE");
                    olho_11.putAtribute("filled", "True");
                    Circle olho_22 = new Circle ("olho_22", 760, 52, 2);
                    olho_22.putAtribute("color", "BLUE");
                    olho_22.putAtribute("filled", "True");
                    Rectangle Borda_ = new Rectangle("Borda_", 725, 25,50,65);
                    Borda_.putAtribute("color", "GREEN");
                    Borda_.putAtribute("hidden", "True");
                    temp = new ArrayList<Figura>();
                    temp.add(corpo_1);
                    temp.add(corpo_2);
                    temp.add(corpo_3);
                    temp.add(corpo_4);
                    temp.add(corpo_5);
                    temp.add(olho_1);
                    temp.add(olho_2);
                    temp.add(olho_11);
                    temp.add(olho_22);
                    temp.add(Borda_);
                    mapa.put("inimigo2",temp);
                    Circle corpo__1 = new Circle ("corpo__1", 750, 847, 25);
                    corpo__1.putAtribute("color", "ORANGE");
                    corpo__1.putAtribute("filled", "True");
                    Rectangle corpo__2 = new Rectangle("corpo__2", 725, 847,50,40);
                    corpo__2.putAtribute("color", "ORANGE");
                    corpo__2.putAtribute("filled", "True");
                    Triangle corpo__3 = new Triangle("corpo__3",725,887,733,877,741,887);
                    corpo__3.putAtribute("color", "BLACK");
                    corpo__3.putAtribute("filled", "True");
                    Triangle corpo__4 = new Triangle("corpo__4",741,887,750,877,758,887);
                    corpo__4.putAtribute("color", "BLACK");
                    corpo__4.putAtribute("filled", "True");
                    Triangle corpo__5 = new Triangle("corpo__5",758,887,767,877,775,887);
                    corpo__5.putAtribute("color", "BLACK");
                    corpo__5.putAtribute("filled", "True");
                    Circle olho__1 = new Circle ("olho__1", 740, 847, 4);
                    olho__1.putAtribute("color", "WHITE");
                    olho__1.putAtribute("filled", "True");
                    Circle olho__2 = new Circle ("olho__2", 760, 847, 4);
                    olho__2.putAtribute("color", "WHITE");
                    olho__2.putAtribute("filled", "True");
                    Circle olho__11 = new Circle ("olho__11", 740, 849, 2);
                    olho__11.putAtribute("color", "BLUE");
                    olho__11.putAtribute("filled", "True");
                    Circle olho__22 = new Circle ("olho__22", 760, 849, 2);
                    olho__22.putAtribute("color", "BLUE");
                    olho__22.putAtribute("filled", "True");
                    Rectangle Borda__ = new Rectangle("Borda__", 725, 822,50,65);
                    Borda__.putAtribute("color", "GREEN");
                    Borda__.putAtribute("hidden", "True");
                    temp = new ArrayList<Figura>();
                    temp.add(corpo__1);
                    temp.add(corpo__2);
                    temp.add(corpo__3);
                    temp.add(corpo__4);
                    temp.add(corpo__5);
                    temp.add(olho__1);
                    temp.add(olho__2);
                    temp.add(olho__11);
                    temp.add(olho__22);
                    temp.add(Borda__);
                    mapa.put("inimigo3",temp);
                    Circle corpo___1 = new Circle ("corpo___1", 50, 847, 25);
                    corpo___1.putAtribute("color", "PINK");
                    corpo___1.putAtribute("filled", "True");
                    Rectangle corpo___2 = new Rectangle("corpo___2", 25, 847,50,40);
                    corpo___2.putAtribute("color", "PINK");
                    corpo___2.putAtribute("filled", "True");
                    Triangle corpo___3 = new Triangle("corpo___3",25,887,33,877,41,887);
                    corpo___3.putAtribute("color", "BLACK");
                    corpo___3.putAtribute("filled", "True");
                    Triangle corpo___4 = new Triangle("corpo___4",41,887,50,877,58,887);
                    corpo___4.putAtribute("color", "BLACK");
                    corpo___4.putAtribute("filled", "True");
                    Triangle corpo___5 = new Triangle("corpo___5",58,887,67,877,75,887);
                    corpo___5.putAtribute("color", "BLACK");
                    corpo___5.putAtribute("filled", "True");
                    Circle olho___1 = new Circle ("olho___1", 40, 847, 4);
                    olho___1.putAtribute("color", "WHITE");
                    olho___1.putAtribute("filled", "True");
                    Circle olho___2 = new Circle ("olho___2", 60, 847, 4);
                    olho___2.putAtribute("color", "WHITE");
                    olho___2.putAtribute("filled", "True");
                    Circle olho___11 = new Circle ("olho___11", 40, 849, 2);
                    olho___11.putAtribute("color", "BLUE");
                    olho___11.putAtribute("filled", "True");
                    Circle olho___22 = new Circle ("olho___22", 60, 849, 2);
                    olho___22.putAtribute("color", "BLUE");
                    olho___22.putAtribute("filled", "True");
                    Rectangle Borda___ = new Rectangle("Borda___", 25, 822,50,65);
                    Borda___.putAtribute("color", "GREEN");
                    Borda___.putAtribute("hidden", "True");
                    temp = new ArrayList<Figura>();
                    temp.add(corpo___1);
                    temp.add(corpo___2);
                    temp.add(corpo___3);
                    temp.add(corpo___4);
                    temp.add(corpo___5);
                    temp.add(olho___1);
                    temp.add(olho___2);
                    temp.add(olho___11);
                    temp.add(olho___22);
                    temp.add(Borda___);
                    mapa.put("inimigo4",temp);
          }
}